// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	settings: {
		stopOtherPlayers: {
			/**
			 * S​t​o​p​ ​o​t​h​e​r​ ​p​l​a​y​e​r​s​ ​w​h​e​n​ ​p​l​a​y​i​n​g
			 */
			title: string
			/**
			 * S​t​o​p​ ​o​t​h​e​r​ ​p​l​a​y​e​r​s​ ​w​h​e​n​ ​p​l​a​y​i​n​g​ ​a​ ​n​e​w​ ​a​u​d​i​o​ ​f​i​l​e
			 */
			description: string
		}
		waveformType: {
			/**
			 * W​a​v​e​f​o​r​m​ ​T​y​p​e
			 */
			title: string
			/**
			 * C​h​o​o​s​e​ ​t​h​e​ ​d​i​s​p​l​a​y​ ​s​t​y​l​e​ ​o​f​ ​t​h​e​ ​a​u​d​i​o​ ​w​a​v​e​f​o​r​m
			 */
			description: string
			options: {
				/**
				 * B​a​r​s
				 */
				bars: string
				/**
				 * E​n​v​e​l​o​p​e
				 */
				envelope: string
				/**
				 * L​i​n​e
				 */
				line: string
				/**
				 * M​i​r​r​o​r
				 */
				mirror: string
				/**
				 * W​a​v​e
				 */
				wave: string
			}
		}
		samplePoints: {
			/**
			 * S​a​m​p​l​e​ ​p​o​i​n​t​s
			 */
			title: string
			/**
			 * S​e​t​ ​t​h​e​ ​n​u​m​b​e​r​ ​o​f​ ​s​a​m​p​l​e​ ​p​o​i​n​t​s​ ​f​o​r​ ​t​h​e​ ​w​a​v​e​f​o​r​m​.​ ​T​h​e​ ​h​i​g​h​e​r​ ​t​h​e​ ​n​u​m​b​e​r​,​ ​t​h​e​ ​m​o​r​e​ ​d​e​t​a​i​l​e​d​ ​t​h​e​ ​w​a​v​e​f​o​r​m​,​ ​b​u​t​ ​t​h​e​ ​p​e​r​f​o​r​m​a​n​c​e​ ​c​o​n​s​u​m​p​t​i​o​n​ ​i​s​ ​a​l​s​o​ ​h​i​g​h​e​r​.
			 */
			description: string
			options: {
				/**
				 * 5​0​ ​(​L​o​w​e​s​t​)
				 */
				'50': string
				/**
				 * 1​0​0​ ​(​L​o​w​)
				 */
				'100': string
				/**
				 * 2​0​0​ ​(​D​e​f​a​u​l​t​)
				 */
				'200': string
				/**
				 * 5​0​0​ ​(​M​e​d​i​u​m​)
				 */
				'500': string
				/**
				 * 1​0​0​0​ ​(​H​i​g​h​)
				 */
				'1000': string
				/**
				 * 2​0​0​0​ ​(​V​e​r​y​ ​H​i​g​h​)
				 */
				'2000': string
				/**
				 * 5​0​0​0​ ​(​E​x​t​r​e​m​e​)
				 */
				'5000': string
			}
		}
	}
}

export type TranslationFunctions = {
	settings: {
		stopOtherPlayers: {
			/**
			 * Stop other players when playing
			 */
			title: () => LocalizedString
			/**
			 * Stop other players when playing a new audio file
			 */
			description: () => LocalizedString
		}
		waveformType: {
			/**
			 * Waveform Type
			 */
			title: () => LocalizedString
			/**
			 * Choose the display style of the audio waveform
			 */
			description: () => LocalizedString
			options: {
				/**
				 * Bars
				 */
				bars: () => LocalizedString
				/**
				 * Envelope
				 */
				envelope: () => LocalizedString
				/**
				 * Line
				 */
				line: () => LocalizedString
				/**
				 * Mirror
				 */
				mirror: () => LocalizedString
				/**
				 * Wave
				 */
				wave: () => LocalizedString
			}
		}
		samplePoints: {
			/**
			 * Sample points
			 */
			title: () => LocalizedString
			/**
			 * Set the number of sample points for the waveform. The higher the number, the more detailed the waveform, but the performance consumption is also higher.
			 */
			description: () => LocalizedString
			options: {
				/**
				 * 50 (Lowest)
				 */
				'50': () => LocalizedString
				/**
				 * 100 (Low)
				 */
				'100': () => LocalizedString
				/**
				 * 200 (Default)
				 */
				'200': () => LocalizedString
				/**
				 * 500 (Medium)
				 */
				'500': () => LocalizedString
				/**
				 * 1000 (High)
				 */
				'1000': () => LocalizedString
				/**
				 * 2000 (Very High)
				 */
				'2000': () => LocalizedString
				/**
				 * 5000 (Extreme)
				 */
				'5000': () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
